#!/usr/bin/env bash
# Loop through the files and directories in the current directory

for file in *
do
  # Check if the file is not hidden (doesn't start with a dot)
  if [[ ! "$file" == .* ]]
  then
    # Extract the part after the first dash
    name_part=$(echo "$file" | cut -d'-' -f2-)
    
    # Display the extracted name
    echo "$name_part"
  fi
done

